// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izphmqfykvtyigsqomvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6cGhtcWZ5a3Z0eWlnc3FvbXZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NjkxNzQsImV4cCI6MjA3MzA0NTE3NH0.63TzRMqUrXkbgSxYwW1A_6P2V5A5hoEfMGmDIQ7tfI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});